### ISSUE TITLE
Visual Studio 2015 Community opens the project, displays a error about DevelopmentWithADot.snk

### ISSUE THREAD

**Issue by akira32chen** [rjperes/DevelopmentWithADot.AspNetSpeechSynthesizer#1]
I download the sample code and use Visual Studio 2015 Community to open the solution file.
When I compile the solution, there is no error. But I run the project of  DevelopmentWithADot.AspNetSpeechSynthesizer.Test, Visual Studio 2015 Community display the error about lacking the DevelopmentWithADot.snk.  Does somebody know where can download this snk file?

```
Severity	Code	Description	Project	File	Line
Error		Error signing output with public key from file '..\..\DevelopmentWithADot.snk' -- File not found.	DevelopmentWithADot.AspNetSpeechSynthesizer	C:\Users\user\Downloads\DevelopmentWithADot.AspNetSpeechSynthesizer-master\DevelopmentWithADot.AspNetSpeechSynthesizer-master\DevelopmentWithADot.AspNetSpeechSynthesizer\CSC	
```

**Comment by rjperes** [comment]
Hi,
You can't download it, it's my private key. You need to disable project signing in the project properties.
